<?php
/**
* @file
* Block Module for displaying a Kmaps Navigator
*/
function kmaps_navigator_help($path, $arg) {
    switch ($path) {
        case "admin/help#kmaps_navigator":
            return '<p>' . t("Kmaps Search and Navigation:  So Helpful!") . '</p>';
            break;
    }
}

/**
* Implements hook_block_info().
*/
function kmaps_navigator_block_info() {
    $blocks['kmaps_navigator_block'] = array(
        'info' => t('KMaps Navigator'),
        'cache' => DRUPAL_NO_CACHE,   // DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function kmaps_navigator_block_view($delta = '') {
    $block = array();

    switch ($delta) {
        case 'kmaps_navigator_block':
            //why?
            drupal_add_library('system', 'drupal.ajax');

            $block['subject'] = '';
            $block['content'] = array(
                '#markup' => theme('kmaps_navigator_block', array(
                    'forums' => 'f',
                    'topics' => 't',
                    'parents' => 'p',
                    'domain' => 'Places',
                    'search' => shanti_kmaps_admin_search_field('kmaps-navigator', 'places'),
                    'filters' => shanti_kmaps_admin_search_filters('kmaps-navigator'),
                )),
                '#attached' => array(
                    'library' => array(
                        'system',
                        'drupal.ajax',
                    ),
                    'libraries_load' => array(
                        array('typeahead'),
                        array('shanti_kmaps_typeahead'),
                        array('json2'),
                        array('fancytree', 'source'),
                        array('shanti_kmaps_tree'),
                    ),
                    'css' => array(
                        SHANTI_KMAPS_ADMIN_PATH . "/css/shanti_kmaps_filter.css",
                        SHANTI_KMAPS_ADMIN_PATH . "/css/shanti_kmaps_picklist.css",
                        SHANTI_KMAPS_ADMIN_PATH . "/css/shanti_kmaps_typeahead.css",
                        drupal_get_path('module', 'kmaps_navigator') . "/css/kmaps_navigator.css",
                    ),
                    'js' => array(
                        SHANTI_KMAPS_ADMIN_PATH . "/js/shanti_kmaps_filter.js",
                        drupal_get_path('module', 'kmaps_navigator') . "/js/kmaps_navigator.js",
                        array(
                            'type' => 'setting',
                            'data' => array(
                                'shanti_kmaps_admin' => array(
                                    'kmaps_filter' => array(
                                        'kmaps-navigator' => array(
                                            'domain' => 'places',
                                            'root_kmap_path' => '',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            );
            break;
    }
    return $block;
}

/**
 * Implements hook_theme()
 *
 */
function kmaps_navigator_theme() {
    $ret = array(
        'kmaps_navigator_block' => array(
            'path' => drupal_get_path('module', 'kmaps_navigator') . '/templates',
            'template' => 'kmaps_navigator_block',
            'variables' => array(
                'forums' => NULL, 'topics' => NULL, 'parents' => NULL, 'domain' => NULL, 'search' => NULL, 'filters' => NULL,
            ),
        ),
    );
    return $ret;
}