<?php
/**
* @file
* Block Module for displaying a Kmaps Navigator
*/
function kmaps_navigator_help($path, $arg) {
    switch ($path) {
        case "admin/help#kmaps_navigator":
            return '<p>' . t("Kmaps Search and Navigation:  So Helpful!") . '</p>';
            break;
    }
}


/**
 * Helper function to call theme
 */
function _kmaps_navigator_block() {
    error_log("_kmaps_navigator_block helper function...");
    $block = array(
        'subject' => '',
        'content' => theme('kmaps_navigator_block', array(
            'forums' => 'f', 'topics' => 't', 'parents' => 'p'
        )),
    );
//    error_log("returning: " . print_r($block,true));
    return $block;
}

/**
 * Implements hook_block_info().
 */
function kmaps_navigator_block_info() {
    error_log("kmaps_navigator_block_info()");
    $blocks['kmaps_navigator_block'] = array(
        // The name that will appear in the block list.
        'info' => t('KMaps Navigator'),
        // Default setting.
        'cache' => DRUPAL_NO_CACHE   // DRUPAL_CACHE_PER_ROLE,
    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function kmaps_navigator_block_view($delta = 'kmaps_navigator_block') {
//    error_log("loading json2: " . print_r(libraries_load('json2'),true));
    error_log("loading fancytree: " . print_r(libraries_load('fancytree','source'),true));
    error_log("loading ajaxsolr: " . print_r(libraries_load('ajaxsolr'),true));
    error_log("loading navigator: " . print_r(drupal_add_js(drupal_get_path('module', 'kmaps_navigator') . "/js/kmaps_navigator.js",array(
            'group' => JS_THEME,
        )),true));
    // drupal_add_js("https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js",array('type' => 'external'));
    // drupal_add_css("https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css",array('type' => 'external'));
    // drupal_add_css("https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css",array('type' => 'external'));

    //Add Ajax library
    drupal_add_library('system', 'drupal.ajax');

    switch ($delta) {
        case 'kmaps_navigator_block':
//            error_log("kmaps navigator block view");
            $block = _kmaps_navigator_block();
//            error_log("kmaps_navigator_block_view returning: " . print_r($block,true));
            return $block;
            break;
        default:
//            error_log("WHY WHY WHY? default block_view case.  delta = " . $delta);
            $block = _kmaps_navigator_block();
            return $block;
            break;
    }
}

/**
 * Implements hook_theme()
 *
 */
function kmaps_navigator_theme() {
    $module_path = drupal_get_path('module', 'kmaps_navigator');
    $base = array(
        'path' => "{$module_path}/templates",
    );
    $ret = array(
        'kmaps_navigator_block' => $base + array(
                // I could define here anything I want
                // It would be called from inside the subpath theme in the module path
                // as file abc.tpl.php
                'template' => 'kmaps_navigator_block',
                // To override I need file
                // 'block--<MODULE_NAME>--<DELTA>.tpl.php'
                // somewhere in my theme's folder
                // (with '-' for '_' in <MODULE_NAME> and <DELTA>)
                // <DELTA> comes from array keys in hook_block_info
                // in this case
                // block--my-module--my-module-block1.tpl.php

                'variables' => array(
                    'forums' => NULL, 'topics' => NULL, 'parents' => NULL
                ),
                '#attached' => array(
                    'libraries_load' => array(
                        array(
                            'fancytree'
                        ),
                        array(
                            'ajaxsolr'
                        )
                    ),
                    'library' => array(
                        'system', 'drupal.ajax'
                    ),
                )
            )
    );

    // error_log("kmaps_navigator_theme returning: " . print_r($ret,true));

    return $ret;

}


